version: '1.0'
name: ci-ubuntu-gitee
displayName: ci-ubuntu-gitee
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - main
    paths:
      precise:
        - goldfish/
        - tests/
        - src/
        - xmake/packages/
        - xmake.lua
        - .workflow/
  push:
    branches:
      precise:
        - main
    paths:
      precise:
        - goldfish/
        - tests/
        - src/
        - xmake/packages/
        - xmake.lua
        - .workflow/

variables:
  XMAKE_MAIN_REPO: 'https://gitee.com/tboox/xmake-repo.git'
  XMAKE_BINARY_REPO: 'https://gitee.com/xmake-mirror/build-artifacts.git'
  XMAKE_ROOT: y

stages:
  - name: build_and_test
    displayName: build_and_test
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build
        displayName: Build and Test
        gccVersion: '8.4'
        commands:
          - env
          - wget https://gitee.com/XmacsLabs/mogan/attach_files/1813514/download -O /tmp/xmake.deb
          - sha1sum /tmp/xmake.deb | grep ac3629bd0fa66f179aef35dc00b7a1c89735651a
          - apt install /tmp/xmake.deb
          - sed -i '/github\.com/d' xmake/packages/s/s7/xmake.lua
          - xmake repo --update
          - sed -i '/github\.com/d' xmake/packages/s/s7/xmake.lua
          - sed -i '/github\.com/d' xmake/packages/t/tbox/xmake.lua
          - xmake config --yes -vD
          - xmake build --yes -vD goldfish
          - bin/goldfish -l tests/test_all.scm
        caches: [
            ~/.xmake/packages
        ]
        notify: []
        strategy:
          retry: '0'
          stepTimeout: 15

