(module scheme.base (let-values)
  (define-syntax let-values
    (lambda (x)
      (syntax-case x ()
        ((_ ((binds exp)) b0 b1 ...)
         (syntax (call-with-values (lambda () exp)
                   (lambda binds b0 b1 ...))))
        ((_ (clause ...) b0 b1 ...)
         (let lp ((clauses (syntax (clause ...)))
                  (ids '())
                  (tmps '()))
           (if (null? clauses)
               (with-syntax (((id ...) ids)
                             ((tmp ...) tmps))
                 (syntax (let ((id tmp) ...)
                           b0 b1 ...)))
               (syntax-case (car clauses) ()
                 (((var ...) exp)
                  (with-syntax (((new-tmp ...) (generate-temporaries 
                                                (syntax (var ...))))
                                ((id ...) ids)
                                ((tmp ...) tmps))
                    (with-syntax ((inner (lp (cdr clauses)
                                             (syntax (var ... id ...))
                                             (syntax (new-tmp ... tmp ...)))))
                      (syntax (call-with-values (lambda () exp)
                                (lambda (new-tmp ...) inner))))))
                 ((vars exp)
                  (with-syntax ((((new-var . new-tmp) ...)
                                 (let lp ((vars (syntax vars)))
                                   (syntax-case vars ()
                                     ((id . rest)
                                      (acons (syntax id)
                                             (car
                                              (generate-temporaries (syntax (id))))
                                             (lp (syntax rest))))
                                     (id (acons (syntax id)
                                                (car
                                                 (generate-temporaries (syntax (id))))
                                                '())))))
                                ((id ...) ids)
                                ((tmp ...) tmps))
                    (with-syntax ((inner (lp (cdr clauses)
                                             (syntax (new-var ... id ...))
                                             (syntax (new-tmp ... tmp ...))))
                                  (args (let lp ((tmps (syntax (new-tmp ...))))
                                          (syntax-case tmps ()
                                            ((id) (syntax id))
                                            ((id . rest) (cons (syntax id)
                                                               (lp (syntax rest))))))))
                      (syntax (call-with-values (lambda () exp)
                                (lambda args inner))))))))))))))

(module demo ()
  (import scheme.base)
  (let-values (((a b) (values 1 2)))
    (display b)
    (newline)))
