(import (liii sys)
        (liii path)
        (liii lint)
        (liii list))

(let ((args (argv)))
  (if (>= (length args) 3)
      (let ((filename (third args)))
        (display filename)
        (display ": ")
        (let ((result (lint-check-brackets (path-read-text filename))))
          (if (eq? (car result) 'matched)
              (display "balanced parentheses\n")
              (display "unbalanced parentheses\n"))))
      (display "Usage: goldfish tools/lint.scm <filename>\n")))